//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input argument is not indexed collection.
        /// </summary>
        internal static string ArgumentIsNotArray {
            get {
                return ResourceManager.GetString("ArgumentIsNotArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER BY item {0} must be the number of a SELECT-list expression.
        /// </summary>
        internal static string BadOrderByItem {
            get {
                return ResourceManager.GetString("BadOrderByItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0} ambiguously defined.
        /// </summary>
        internal static string ColumnAmbiguoslyDefined {
            get {
                return ResourceManager.GetString("ColumnAmbiguoslyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For fixed length text schema column data type declaration is requred.
        /// </summary>
        internal static string ColumnDataTypeRequred {
            get {
                return ResourceManager.GetString("ColumnDataTypeRequred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataReader is not open.
        /// </summary>
        internal static string DataReaderNotOpen {
            get {
                return ResourceManager.GetString("DataReaderNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default datasource is undefined.
        /// </summary>
        internal static string DefaultDataSourceNotDefined {
            get {
                return ResourceManager.GetString("DefaultDataSourceNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMLQUERY expression contains duplicate context item.
        /// </summary>
        internal static string DuplicateContextItem {
            get {
                return ResourceManager.GetString("DuplicateContextItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic table &quot;{0}&quot; is empty set..
        /// </summary>
        internal static string DyntableEmpty {
            get {
                return ResourceManager.GetString("DyntableEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape char must be a string one character length.
        /// </summary>
        internal static string EscapeCharToLong {
            get {
                return ResourceManager.GetString("EscapeCharToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected argument in function {0}.
        /// </summary>
        internal static string ExpectedArgument {
            get {
                return ResourceManager.GetString("ExpectedArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Expecting column width for fixed length text schema.
        /// </summary>
        internal static string ExpectedWidthInSchemaIni {
            get {
                return ResourceManager.GetString("ExpectedWidthInSchemaIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is not found in current path.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group function not allowed in where clause.
        /// </summary>
        internal static string GroupFunctionNotAllowed {
            get {
                return ResourceManager.GetString("GroupFunctionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualified join is illegal for dynamic table.
        /// </summary>
        internal static string IllegalJoin {
            get {
                return ResourceManager.GetString("IllegalJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prefix {0} is impossible for name {0}.
        /// </summary>
        internal static string ImpossiblePrefix {
            get {
                return ResourceManager.GetString("ImpossiblePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent datatypes expected {0} got {1}.
        /// </summary>
        internal static string InconsistentDatatypes {
            get {
                return ResourceManager.GetString("InconsistentDatatypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent nested types.
        /// </summary>
        internal static string InconsistentNestedTypes {
            get {
                return ResourceManager.GetString("InconsistentNestedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corresponed subqueris must have equal number result columns with same datatypes.
        /// </summary>
        internal static string IncorrectSubqueries {
            get {
                return ResourceManager.GetString("IncorrectSubqueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token {0} is invalid axis.
        /// </summary>
        internal static string InvalidAxisToken {
            get {
                return ResourceManager.GetString("InvalidAxisToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument of function {0}.
        /// </summary>
        internal static string InvalidFunctionArgument {
            get {
                return ResourceManager.GetString("InvalidFunctionArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Invalid identifier.
        /// </summary>
        internal static string InvalidIdentifier {
            get {
                return ResourceManager.GetString("InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For {0} datasources identifier must be a &quot;{1}&quot;.
        /// </summary>
        internal static string InvalidIdentifierFormat {
            get {
                return ResourceManager.GetString("InvalidIdentifierFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option NIL ON NULL and NULL ON NULL  is invalid for attribute {0}.
        /// </summary>
        internal static string InvalidOptionForXmlAttribute {
            get {
                return ResourceManager.GetString("InvalidOptionForXmlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only column names allowed in XMLAgg ORDER BY clause.
        /// </summary>
        internal static string InvalidOrdinalInXMLAgg {
            get {
                return ResourceManager.GetString("InvalidOrdinalInXMLAgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid table alias name {0}.
        /// </summary>
        internal static string InvalidTableAlias {
            get {
                return ResourceManager.GetString("InvalidTableAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid text file format: no delimiter after double-quote. LineNo = {0}. LinePos = {1}..
        /// </summary>
        internal static string InvalidTextFileFormat {
            get {
                return ResourceManager.GetString("InvalidTextFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing FROM clause.
        /// </summary>
        internal static string MissingFromClause {
            get {
                return ResourceManager.GetString("MissingFromClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node &quot;{0}&quot; is not exist.
        /// </summary>
        internal static string NodeNotExists {
            get {
                return ResourceManager.GetString("NodeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument of function $text must be a XmlNode.
        /// </summary>
        internal static string NodeTextInvalidArgument {
            get {
                return ResourceManager.GetString("NodeTextInvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - No one file was found..
        /// </summary>
        internal static string NoOneFileWasFound {
            get {
                return ResourceManager.GetString("NoOneFileWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a group by expression &quot;{0}&quot;.
        /// </summary>
        internal static string NotAGroupByExpr {
            get {
                return ResourceManager.GetString("NotAGroupByExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values is not comparable.
        /// </summary>
        internal static string NotComparableValues {
            get {
                return ResourceManager.GetString("NotComparableValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough values in predicate.
        /// </summary>
        internal static string NotEnoughValues {
            get {
                return ResourceManager.GetString("NotEnoughValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a single-group group function &quot;{0}&quot;.
        /// </summary>
        internal static string NotSingleGroupFunc {
            get {
                return ResourceManager.GetString("NotSingleGroupFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t dereference {0}: value {1} is not structured object.
        /// </summary>
        internal static string NotStructuredObject {
            get {
                return ResourceManager.GetString("NotStructuredObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} of function {1} must be aliased.
        /// </summary>
        internal static string ParameterMustBeAliased {
            get {
                return ResourceManager.GetString("ParameterMustBeAliased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The row state is &apos;recycled&apos;.
        /// </summary>
        internal static string RowRecycled {
            get {
                return ResourceManager.GetString("RowRecycled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single row subquery return more than one row.
        /// </summary>
        internal static string SingleRowSubquery {
            get {
                return ResourceManager.GetString("SingleRowSubquery", resourceCulture);
            }
        }
        
        internal static byte[] SQLX_Config {
            get {
                object obj = ResourceManager.GetObject("SQLX_Config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error: {0}.
        /// </summary>
        internal static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table or view {0} does not exists.
        /// </summary>
        internal static string TableDoesNotExists {
            get {
                return ResourceManager.GetString("TableDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many arguments in function {0}.
        /// </summary>
        internal static string TooManyArguments {
            get {
                return ResourceManager.GetString("TooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many values.
        /// </summary>
        internal static string TooManyValues {
            get {
                return ResourceManager.GetString("TooManyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} is undefined for object type {1}.
        /// </summary>
        internal static string UndefinedProperty {
            get {
                return ResourceManager.GetString("UndefinedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $rownum() allowed only in select expression.
        /// </summary>
        internal static string UnexpectedRownum {
            get {
                return ResourceManager.GetString("UnexpectedRownum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end-of-file in double-quoted literal. LineNo = {0}. LinePos = {1}..
        /// </summary>
        internal static string UnexpectedTextFileEOF {
            get {
                return ResourceManager.GetString("UnexpectedTextFileEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end-of-line in double-quoted literal. LineNo = {0}. LinePos = {1}..
        /// </summary>
        internal static string UnexpectedTextFileEOL {
            get {
                return ResourceManager.GetString("UnexpectedTextFileEOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasource name {0} is unknown or not exists.
        /// </summary>
        internal static string UnknownDataSource {
            get {
                return ResourceManager.GetString("UnknownDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &quot;{0}&quot; can not be converted to type {1}. LineNo = {2}. LinePos = {3}..
        /// </summary>
        internal static string ValueConvertException {
            get {
                return ResourceManager.GetString("ValueConvertException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; - The Xml Query context must be a node..
        /// </summary>
        internal static string XmlQueryContextMustBeANode {
            get {
                return ResourceManager.GetString("XmlQueryContextMustBeANode", resourceCulture);
            }
        }
    }
}
