//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEngine.XQuery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataEngine.XQuery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad character ref constant &amp;#{0}{1};.
        /// </summary>
        internal static string BadCharRef {
            get {
                return ResourceManager.GetString("BadCharRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator {0}  is not defined for arguments of type {1} and {2}.
        /// </summary>
        internal static string BinaryOperatorNotDefined {
            get {
                return ResourceManager.GetString("BinaryOperatorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context item cannot be defined.
        /// </summary>
        internal static string ContextItemNotDefined {
            get {
                return ResourceManager.GetString("ContextItemNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected atomic value.
        /// </summary>
        internal static string ExpectedAtomicValue {
            get {
                return ResourceManager.GetString("ExpectedAtomicValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {{ after {0} {1}.
        /// </summary>
        internal static string ExpectedBlockStart {
            get {
                return ResourceManager.GetString("ExpectedBlockStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected module declaration.
        /// </summary>
        internal static string ExpectedModuleDecl {
            get {
                return ResourceManager.GetString("ExpectedModuleDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected NCName after *:.
        /// </summary>
        internal static string ExpectedNCName {
            get {
                return ResourceManager.GetString("ExpectedNCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} qualified name &apos;{1}&apos; must have a prefix.
        /// </summary>
        internal static string ExpectedQNamePrefix {
            get {
                return ResourceManager.GetString("ExpectedQNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected prefix $ after {0}.
        /// </summary>
        internal static string ExpectedVariablePrefix {
            get {
                return ResourceManager.GetString("ExpectedVariablePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting {0} after QName.
        /// </summary>
        internal static string ExpectingCharAfterQName {
            get {
                return ResourceManager.GetString("ExpectingCharAfterQName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External variable {0} not set before run command.
        /// </summary>
        internal static string ExternalVariableNotSet {
            get {
                return ResourceManager.GetString("ExternalVariableNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is not found in current path.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division by zero.
        /// </summary>
        internal static string FOAR0001 {
            get {
                return ResourceManager.GetString("FOAR0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric operation overflow/underflow.
        /// </summary>
        internal static string FOAR0002 {
            get {
                return ResourceManager.GetString("FOAR0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QName {0} has null namespace but non-empty prefix.
        /// </summary>
        internal static string FOCA0002 {
            get {
                return ResourceManager.GetString("FOCA0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NaN supplied as float/double value.
        /// </summary>
        internal static string FOCA0005 {
            get {
                return ResourceManager.GetString("FOCA0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XML character [x{0}].
        /// </summary>
        internal static string FOCH0001 {
            get {
                return ResourceManager.GetString("FOCH0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No context document.
        /// </summary>
        internal static string FODC0001 {
            get {
                return ResourceManager.GetString("FODC0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument &apos;{0}&apos; to fn:collection.
        /// </summary>
        internal static string FODC0004 {
            get {
                return ResourceManager.GetString("FODC0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overflow/underflow in date/time operation.
        /// </summary>
        internal static string FODT0001 {
            get {
                return ResourceManager.GetString("FODT0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overflow/underflow in duration operation.
        /// </summary>
        internal static string FODT0002 {
            get {
                return ResourceManager.GetString("FODT0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid timezone value {0}.
        /// </summary>
        internal static string FODT0003 {
            get {
                return ResourceManager.GetString("FODT0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidentified error.
        /// </summary>
        internal static string FOER0000 {
            get {
                return ResourceManager.GetString("FOER0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base-uri not defined in the static context.
        /// </summary>
        internal static string FONS0005 {
            get {
                return ResourceManager.GetString("FONS0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;&quot;{0}&quot;&apos; is an invalid argument for constructor/cast {1}.
        /// </summary>
        internal static string FORG0001 {
            get {
                return ResourceManager.GetString("FORG0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;zero-or-one&apos; was called with a sequence containing more than one item.
        /// </summary>
        internal static string FORG0003 {
            get {
                return ResourceManager.GetString("FORG0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;one-or-more&apos; was called with a sequence containing no items.
        /// </summary>
        internal static string FORG0004 {
            get {
                return ResourceManager.GetString("FORG0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;exactly-one&apos; was called with a sequence containing zero or more than one item.
        /// </summary>
        internal static string FORG0005 {
            get {
                return ResourceManager.GetString("FORG0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; was called with invalid argument type {1}.
        /// </summary>
        internal static string FORG0006 {
            get {
                return ResourceManager.GetString("FORG0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both arguments to fn:dateTime have a specified timezone.
        /// </summary>
        internal static string FORG0008 {
            get {
                return ResourceManager.GetString("FORG0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in resolving a relative URI against a base URI in fn:resolve-uri.
        /// </summary>
        internal static string FORG0009 {
            get {
                return ResourceManager.GetString("FORG0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression {0} matches zero-length string.
        /// </summary>
        internal static string FORX0003 {
            get {
                return ResourceManager.GetString("FORX0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid replacement string {0}.
        /// </summary>
        internal static string FORX0004 {
            get {
                return ResourceManager.GetString("FORX0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument node {0} does not have a typed value.
        /// </summary>
        internal static string FOTY0012 {
            get {
                return ResourceManager.GetString("FOTY0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content sequence of a document node may not contain an attribute node.
        /// </summary>
        internal static string InvalidAttributeSequence {
            get {
                return ResourceManager.GetString("InvalidAttributeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string {0} has invalid format for type {1}.
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target xml is invalid for processing instruction.
        /// </summary>
        internal static string InvalidPITarget {
            get {
                return ResourceManager.GetString("InvalidPITarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The regular expression &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string InvalidRegularExpr {
            get {
                return ResourceManager.GetString("InvalidRegularExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression flags {0}.
        /// </summary>
        internal static string InvalidRegularExpressionFlags {
            get {
                return ResourceManager.GetString("InvalidRegularExpressionFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one item in sequence in atomic expression.
        /// </summary>
        internal static string MoreThanOneItem {
            get {
                return ResourceManager.GetString("MoreThanOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration finished.
        /// </summary>
        internal static string Sch_EnumFinished {
            get {
                return ResourceManager.GetString("Sch_EnumFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration not started.
        /// </summary>
        internal static string Sch_EnumNotStarted {
            get {
                return ResourceManager.GetString("Sch_EnumNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator {0}  is not defined for argument of type {1}.
        /// </summary>
        internal static string UnaryOperatorNotDefined {
            get {
                return ResourceManager.GetString("UnaryOperatorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected char {0}.
        /// </summary>
        internal static string UnexpectedChar {
            get {
                return ResourceManager.GetString("UnexpectedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file.
        /// </summary>
        internal static string UnexpectedEOF {
            get {
                return ResourceManager.GetString("UnexpectedEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable  {0} is not defined as external.
        /// </summary>
        internal static string UnknownExternalVariable {
            get {
                return ResourceManager.GetString("UnknownExternalVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported normalization form {0}.
        /// </summary>
        internal static string UnsupportedNormalizationForm {
            get {
                return ResourceManager.GetString("UnsupportedNormalizationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context item cannot be defined.
        /// </summary>
        internal static string XPDY0002 {
            get {
                return ResourceManager.GetString("XPDY0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error. {0}.
        /// </summary>
        internal static string XPST0003 {
            get {
                return ResourceManager.GetString("XPST0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected type {0}.
        /// </summary>
        internal static string XPST0004 {
            get {
                return ResourceManager.GetString("XPST0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qname {0} is not defined.
        /// </summary>
        internal static string XPST0008 {
            get {
                return ResourceManager.GetString("XPST0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos;/{1} was not found in namespace &apos;{2}&apos;.
        /// </summary>
        internal static string XPST0017 {
            get {
                return ResourceManager.GetString("XPST0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type name &apos;{0}&apos; has been used as an atomic type in a sequence type, but is not defined in the in-scope schema types as an atomic type.
        /// </summary>
        internal static string XPST0051 {
            get {
                return ResourceManager.GetString("XPST0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast to {0}. The target type of a cast or castable expression must be an atomic type that is in the in-scope schema types and is not xs:NOTATION or xs:anyAtomicType, optionally followed by the occurrence indicator &quot;?&quot;.
        /// </summary>
        internal static string XPST0080 {
            get {
                return ResourceManager.GetString("XPST0080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prefix &apos;{0}&apos; cannot be expanded into a namespace URI by using the statically known namespaces.
        /// </summary>
        internal static string XPST0081 {
            get {
                return ResourceManager.GetString("XPST0081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic type {0} of a value does not match a required type {1}.
        /// </summary>
        internal static string XPTY0004 {
            get {
                return ResourceManager.GetString("XPTY0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only string literals can be cast to type {0}.
        /// </summary>
        internal static string XPTY0004_CAST {
            get {
                return ResourceManager.GetString("XPTY0004_CAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the last step in a path expression contains both nodes and atomic values {0}.
        /// </summary>
        internal static string XPTY0018 {
            get {
                return ResourceManager.GetString("XPTY0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of a step in path expression must not be an atomic value {0}.
        /// </summary>
        internal static string XPTY0019 {
            get {
                return ResourceManager.GetString("XPTY0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element constructor &quot;{0}&quot; contains a duplicate attribute node &quot;{1}&quot;.
        /// </summary>
        internal static string XQDY0025 {
            get {
                return ResourceManager.GetString("XQDY0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the content expression of a computed processing instruction constructor contains the string &quot;?&gt;&quot;.
        /// </summary>
        internal static string XQDY0026 {
            get {
                return ResourceManager.GetString("XQDY0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node name of a computed attribute may not be &apos;xmlns&apos; because attribute constructors cannot create namespaces.
        /// </summary>
        internal static string XQDY0044 {
            get {
                return ResourceManager.GetString("XQDY0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The computed processing instruction target cannot be equal to &quot;XML&quot; in any combination of upper or lower case.
        /// </summary>
        internal static string XQDY0064 {
            get {
                return ResourceManager.GetString("XQDY0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the content expression of a computed comment constructor contains two adjacent hyphens or ends with a hyphen.
        /// </summary>
        internal static string XQDY0072 {
            get {
                return ResourceManager.GetString("XQDY0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace bound to prefix &apos;{0}&apos; must be a URI literal.  Enclosed expressions are not permitted..
        /// </summary>
        internal static string XQST0022 {
            get {
                return ResourceManager.GetString("XQST0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XQuery version &apos;{0}&apos; is not supported by this implementation.
        /// </summary>
        internal static string XQST0031 {
            get {
                return ResourceManager.GetString("XQST0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module prolog contains more than one base URI declaration.
        /// </summary>
        internal static string XQST0032 {
            get {
                return ResourceManager.GetString("XQST0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module contains multiple bindings for the same namespace prefix {0}..
        /// </summary>
        internal static string XQST0033 {
            get {
                return ResourceManager.GetString("XQST0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; in namespace &apos;{1}&apos; has already been declared with the same number of arguments.
        /// </summary>
        internal static string XQST0034 {
            get {
                return ResourceManager.GetString("XQST0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module prolog contains more than one default collation declaration, or the value specified by a default collation declaration is not present in statically known collations.
        /// </summary>
        internal static string XQST0038 {
            get {
                return ResourceManager.GetString("XQST0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function declaration has more than one parameter with name &apos;{0}&apos;.
        /// </summary>
        internal static string XQST0039 {
            get {
                return ResourceManager.GetString("XQST0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; is a duplicate.  Attributes specified by a direct  element constructor must have distinct expanded qualified names..
        /// </summary>
        internal static string XQST0040 {
            get {
                return ResourceManager.GetString("XQST0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; cannot be declared in the namespace &apos;{1}&apos;.
        /// </summary>
        internal static string XQST0045 {
            get {
                return ResourceManager.GetString("XQST0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple module imports in the same Prolog specify the same target namespace {0}.
        /// </summary>
        internal static string XQST0047 {
            get {
                return ResourceManager.GetString("XQST0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable {0} is already defined in module.
        /// </summary>
        internal static string XQST0049 {
            get {
                return ResourceManager.GetString("XQST0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} variable depends on itself.
        /// </summary>
        internal static string XQST0054 {
            get {
                return ResourceManager.GetString("XQST0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prolog must not contain more than one copy-namespaces declaration.
        /// </summary>
        internal static string XQST0055 {
            get {
                return ResourceManager.GetString("XQST0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple schema imports specify the same target namespace {0}.
        /// </summary>
        internal static string XQST0058 {
            get {
                return ResourceManager.GetString("XQST0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation is unable to process a schema or module import by finding a schema or module with the specified target namespace {0}..
        /// </summary>
        internal static string XQST0059 {
            get {
                return ResourceManager.GetString("XQST0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module prolog contains more than one ordering mode declaration.
        /// </summary>
        internal static string XQST0065 {
            get {
                return ResourceManager.GetString("XQST0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module contains more than one default element/type namespace declaration, or more than one default function namespace declaration..
        /// </summary>
        internal static string XQST0066 {
            get {
                return ResourceManager.GetString("XQST0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module prolog contains more than one construction declaration.
        /// </summary>
        internal static string XQST0067 {
            get {
                return ResourceManager.GetString("XQST0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module prolog contains more than one boundary-space declaration.
        /// </summary>
        internal static string XQST0068 {
            get {
                return ResourceManager.GetString("XQST0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module  prolog contains more than one empty order declaration.
        /// </summary>
        internal static string XQST0069 {
            get {
                return ResourceManager.GetString("XQST0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A namespace URI {0} is bound to the predefined prefix xmlns, or if a namespace URI other than http://www.w3.org/XML/1998/namespace is bound to the prefix xml, or if the prefix xml is bound to a namespace URI other than http://www.w3.org/XML/1998/namespace..
        /// </summary>
        internal static string XQST0070 {
            get {
                return ResourceManager.GetString("XQST0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph of module imports contains a cycle in file {0}.
        /// </summary>
        internal static string XQST0073 {
            get {
                return ResourceManager.GetString("XQST0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not identify a collation that is present in statically known collations.
        /// </summary>
        internal static string XQST0076 {
            get {
                return ResourceManager.GetString("XQST0076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String literal &apos;{0}&apos; is not a valid encoding name.
        /// </summary>
        internal static string XQST0087 {
            get {
                return ResourceManager.GetString("XQST0087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The literal that specifies the target namespace in a module import or a module declaration is of zero length.
        /// </summary>
        internal static string XQST0088 {
            get {
                return ResourceManager.GetString("XQST0088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bound variable &apos;{0}&apos; in a FLWOR expression must be distinct from the positional variable.
        /// </summary>
        internal static string XQST0089 {
            get {
                return ResourceManager.GetString("XQST0089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content sequence in an element constructor contains an attribute node &quot;{0}&quot; following a node that is not an attribute node.
        /// </summary>
        internal static string XQTY0024 {
            get {
                return ResourceManager.GetString("XQTY0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument of a validate expression does not evaluate to exactly one document or element node.
        /// </summary>
        internal static string XQTY0030 {
            get {
                return ResourceManager.GetString("XQTY0030", resourceCulture);
            }
        }
    }
}
