//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEngine.XQuery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataEngine.XQuery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad character ref constant &amp;#{0}{1};.
        /// </summary>
        internal static string BadCharRef {
            get {
                return ResourceManager.GetString("BadCharRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context item cannot be defined.
        /// </summary>
        internal static string ContextItemNotDefined {
            get {
                return ResourceManager.GetString("ContextItemNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected atomic value.
        /// </summary>
        internal static string ExpectedAtomicValue {
            get {
                return ResourceManager.GetString("ExpectedAtomicValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {{ after {0} {1}.
        /// </summary>
        internal static string ExpectedBlockStart {
            get {
                return ResourceManager.GetString("ExpectedBlockStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected module declaration.
        /// </summary>
        internal static string ExpectedModuleDecl {
            get {
                return ResourceManager.GetString("ExpectedModuleDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected NCName after *:.
        /// </summary>
        internal static string ExpectedNCName {
            get {
                return ResourceManager.GetString("ExpectedNCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected prefix $ after {0}.
        /// </summary>
        internal static string ExpectedVariablePrefix {
            get {
                return ResourceManager.GetString("ExpectedVariablePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting {0} after QName.
        /// </summary>
        internal static string ExpectingCharAfterQName {
            get {
                return ResourceManager.GetString("ExpectingCharAfterQName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is not found in current path.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid lexical value {0}.
        /// </summary>
        internal static string FOCA0002 {
            get {
                return ResourceManager.GetString("FOCA0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument &apos;{0}&apos; to fn:collection.
        /// </summary>
        internal static string FODC0004 {
            get {
                return ResourceManager.GetString("FODC0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;zero-or-one&apos; was called with a sequence containing more than one item.
        /// </summary>
        internal static string FORG0003 {
            get {
                return ResourceManager.GetString("FORG0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;one-or-more&apos; was called with a sequence containing no items.
        /// </summary>
        internal static string FORG0004 {
            get {
                return ResourceManager.GetString("FORG0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;exactly-one&apos; was called with a sequence containing zero or more than one item.
        /// </summary>
        internal static string FORG0005 {
            get {
                return ResourceManager.GetString("FORG0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string {0} has invalid format for type {1}.
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target xml is invalid for processing instruction.
        /// </summary>
        internal static string InvalidPITarget {
            get {
                return ResourceManager.GetString("InvalidPITarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression flags {0}.
        /// </summary>
        internal static string InvalidRegularExpressionFlags {
            get {
                return ResourceManager.GetString("InvalidRegularExpressionFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one item in sequence in atomic expression.
        /// </summary>
        internal static string MoreThanOneItem {
            get {
                return ResourceManager.GetString("MoreThanOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module prolog contains more than one option {0} declaration.
        /// </summary>
        internal static string OptionRedeclared {
            get {
                return ResourceManager.GetString("OptionRedeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration finished.
        /// </summary>
        internal static string Sch_EnumFinished {
            get {
                return ResourceManager.GetString("Sch_EnumFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration not started.
        /// </summary>
        internal static string Sch_EnumNotStarted {
            get {
                return ResourceManager.GetString("Sch_EnumNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected char {0}.
        /// </summary>
        internal static string UnexpectedChar {
            get {
                return ResourceManager.GetString("UnexpectedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file.
        /// </summary>
        internal static string UnexpectedEOF {
            get {
                return ResourceManager.GetString("UnexpectedEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable  {0} is not defined as external.
        /// </summary>
        internal static string UnknownExternalVariable {
            get {
                return ResourceManager.GetString("UnknownExternalVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported normalization form {0}.
        /// </summary>
        internal static string UnsupportedNormalizationForm {
            get {
                return ResourceManager.GetString("UnsupportedNormalizationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context item cannot be defined.
        /// </summary>
        internal static string XPDY0002 {
            get {
                return ResourceManager.GetString("XPDY0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected type {0}.
        /// </summary>
        internal static string XPST0004 {
            get {
                return ResourceManager.GetString("XPST0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qname {0} is not defined.
        /// </summary>
        internal static string XPST0008 {
            get {
                return ResourceManager.GetString("XPST0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos;/{1} was not found in namespace &apos;{2}&apos;.
        /// </summary>
        internal static string XPST0017 {
            get {
                return ResourceManager.GetString("XPST0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prefix &apos;{0}&apos; cannot be expanded into a namespace URI by using the statically known namespaces.
        /// </summary>
        internal static string XPST0081 {
            get {
                return ResourceManager.GetString("XPST0081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic type {0} of a value does not match a required type {1}.
        /// </summary>
        internal static string XPTY0004 {
            get {
                return ResourceManager.GetString("XPTY0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of a step in path expression must not be an atomic value {0}.
        /// </summary>
        internal static string XPTY0019 {
            get {
                return ResourceManager.GetString("XPTY0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module prolog contains more than one base URI declaration.
        /// </summary>
        internal static string XQST0032 {
            get {
                return ResourceManager.GetString("XQST0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module contains multiple bindings for the same namespace prefix {0}..
        /// </summary>
        internal static string XQST0033 {
            get {
                return ResourceManager.GetString("XQST0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; in namespace &apos;{1}&apos; has already been declared with the same number of arguments.
        /// </summary>
        internal static string XQST0034 {
            get {
                return ResourceManager.GetString("XQST0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module prolog contains more than one default collation declaration, or the value specified by a default collation declaration is not present in statically known collations.
        /// </summary>
        internal static string XQST0038 {
            get {
                return ResourceManager.GetString("XQST0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &apos;{0}&apos; cannot be declared in the namespace &apos;{1}&apos;.
        /// </summary>
        internal static string XQST0045 {
            get {
                return ResourceManager.GetString("XQST0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable {0} is already defined in module.
        /// </summary>
        internal static string XQST0049 {
            get {
                return ResourceManager.GetString("XQST0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation is unable to process a schema or module import by finding a schema or module with the specified target namespace {0}..
        /// </summary>
        internal static string XQST0059 {
            get {
                return ResourceManager.GetString("XQST0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module prolog contains more than one ordering mode declaration.
        /// </summary>
        internal static string XQST0065 {
            get {
                return ResourceManager.GetString("XQST0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module contains more than one default element/type namespace declaration, or more than one default function namespace declaration..
        /// </summary>
        internal static string XQST0066 {
            get {
                return ResourceManager.GetString("XQST0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module prolog contains more than one construction declaration.
        /// </summary>
        internal static string XQST0067 {
            get {
                return ResourceManager.GetString("XQST0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module prolog contains more than one boundary-space declaration.
        /// </summary>
        internal static string XQST0068 {
            get {
                return ResourceManager.GetString("XQST0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module  prolog contains more than one empty order declaration.
        /// </summary>
        internal static string XQST0069 {
            get {
                return ResourceManager.GetString("XQST0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A namespace URI {0} is bound to the predefined prefix xmlns, or if a namespace URI other than http://www.w3.org/XML/1998/namespace is bound to the prefix xml, or if the prefix xml is bound to a namespace URI other than http://www.w3.org/XML/1998/namespace..
        /// </summary>
        internal static string XQST0070 {
            get {
                return ResourceManager.GetString("XQST0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The literal that specifies the target namespace in a module import or a module declaration is of zero length.
        /// </summary>
        internal static string XQST0088 {
            get {
                return ResourceManager.GetString("XQST0088", resourceCulture);
            }
        }
    }
}
